<?php
header('Content-Type: application/json');
require_once '../../db.php';
require_once '../../functions.php';

$prompt = isset($_POST['prompt']) ? sanitize($_POST['prompt']) : '';

if (empty($prompt)) {
    echo json_encode(['success' => false, 'error' => 'Prompt is empty']);
    exit();
}

$guide = "<h3>AI Study Plan: " . htmlspecialchars($prompt) . "</h3>";
$guide .= "<p>Here is your personalized learning roadmap generated by SkillSphere Copilot:</p>";
$guide .= "<ul>";
$guide .= "<li><strong>Phase 1: Foundations</strong> — Read core specs, set up your local development container, and code simple hello-world iterations.</li>";
$guide .= "<li><strong>Phase 2: Intermediate Projects</strong> — Integrate APIs, connect databases (PostgreSQL/MySQL), and write simple test sweeps.</li>";
$guide .= "<li><strong>Phase 3: Production Scale</strong> — Implement caching (Redis), Dockerize your app, configure CI/CD pipelines, and deploy.</li>";
$guide .= "</ul>";
$guide .= "<p>Check out our corresponding course catalog items to get hands-on workspace environments!</p>";

echo json_encode(['success' => true, 'guide' => $guide]);
?>
